# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='config',
  serialized_pb=_b('\n\x0c\x63onfig.proto\x12\x06\x63onfig\"\xad\x02\n\x06\x43onfig\x12\x17\n\x06option\x18\x01 \x01(\t:\x07sim.out\x12\x17\n\x0btotal_cores\x18\x02 \x01(\x05:\x02\x36\x34\x12\x18\n\rnum_processes\x18\x03 \x01(\x05:\x01\x31\x12\x1c\n\x14\x65nable_core_modeling\x18\x04 \x02(\x08\x12\x1d\n\x15\x65nable_power_modeling\x18\x05 \x02(\x08\x12\"\n\x14\x65nable_area_modeling\x18\x06 \x01(\x08:\x04true\x12\x1f\n\x11\x65nable_shared_mem\x18\x07 \x01(\x08:\x04true\x12\x30\n\x04mode\x18\x08 \x01(\x0e\x32\x1c.config.Config.SimulatorMode:\x04\x66ull\"#\n\rSimulatorMode\x12\x08\n\x04\x66ull\x10\x00\x12\x08\n\x04lite\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONFIG_SIMULATORMODE = _descriptor.EnumDescriptor(
  name='SimulatorMode',
  full_name='config.Config.SimulatorMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='full', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='lite', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=291,
  serialized_end=326,
)
_sym_db.RegisterEnumDescriptor(_CONFIG_SIMULATORMODE)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='config.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='option', full_name='config.Config.option', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("sim.out").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_cores', full_name='config.Config.total_cores', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=64,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_processes', full_name='config.Config.num_processes', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_core_modeling', full_name='config.Config.enable_core_modeling', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_power_modeling', full_name='config.Config.enable_power_modeling', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_area_modeling', full_name='config.Config.enable_area_modeling', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_shared_mem', full_name='config.Config.enable_shared_mem', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='config.Config.mode', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIG_SIMULATORMODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=326,
)

_CONFIG.fields_by_name['mode'].enum_type = _CONFIG_SIMULATORMODE
_CONFIG_SIMULATORMODE.containing_type = _CONFIG
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:config.Config)
  ))
_sym_db.RegisterMessage(Config)


# @@protoc_insertion_point(module_scope)
